"""Generate Phase 1.7 verification and Phase 2 data-readiness reports."""

from __future__ import annotations

import csv
from datetime import date
from pathlib import Path
from typing import Any


REVIEWED = {"MANUALLY_REVIEWED", "FIELD_VERIFIED"}


def _reviewed(item: dict[str, Any]) -> bool:
    return item["properties"].get("verificationStatus") in REVIEWED


def _display(item: dict[str, Any]) -> str:
    props = item["properties"]
    return props.get("displayName") or props.get("name", "")


def _confirmed_dormitories(dataset_dir: Path) -> list[dict[str, str]]:
    path = dataset_dir / "manual" / "dormitory-review.csv"
    if not path.is_file():
        return []
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return [
            row for row in csv.DictReader(handle)
            if row.get("confirmed_number", "").strip()
            and row.get("confirmed_display_name", "").strip()
            and row.get("status", "").strip() in REVIEWED
        ]


def generate_readiness_report(
    layers: dict[str, list[dict[str, Any]]], topology: dict[str, Any],
    naming: dict[str, Any], validation: dict[str, Any], dataset_dir: Path,
) -> dict[str, Any]:
    all_items = [item for values in layers.values() for item in values]
    buildings, pois = layers["buildings"], layers["pois"]
    manual_reviewed = sum(
        item["properties"].get("verificationStatus") == "MANUALLY_REVIEWED"
        for item in all_items
    )
    field_verified = sum(
        item["properties"].get("verificationStatus") == "FIELD_VERIFIED"
        for item in all_items
    )
    dormitories = _confirmed_dormitories(dataset_dir)
    teaching = [item for item in buildings if _display(item) in {f"教{number}" for number in range(1, 6)}]
    library = [item for item in buildings if _display(item) == "图书馆"]
    dining = [item for item in pois if _display(item) in {"一食堂", "二食堂", "三食堂"}]
    administration = [item for item in buildings if _display(item) in {"行政南楼", "行政北楼"}]
    gates = [
        item for item in all_items
        if _display(item) in {"南门", "北门"} and item["properties"].get("featureType") in {"POI", "ENTRANCE"}
    ]
    intersection_p0 = topology.get("intersectionPriority", {}).get("P0", 0)
    topology_p0 = topology.get("qualityMetrics", {}).get("roadP0TopologyIssueCount", 0)

    phase2_blockers = []
    if sum(_reviewed(item) for item in teaching) < 5:
        phase2_blockers.append("教1—教5名称与 Polygon 对应尚未经过用户人工确认")
    if sum(_reviewed(item) for item in library) < 1:
        phase2_blockers.append("图书馆名称与位置尚未经过用户人工确认")
    if sum(_reviewed(item) for item in dining) < 3:
        phase2_blockers.append("一、二、三食堂的用户侧 POI 尚未经过人工确认")
    if sum(_reviewed(item) for item in administration) < 2:
        phase2_blockers.append("行政南楼/北楼的空间映射仍是候选")
    if sum(_reviewed(item) for item in gates) < 2:
        phase2_blockers.append("南门/北门尚无已确认的可搜索对象")
    if len(dormitories) == 0:
        phase2_blockers.append("宿舍编号尚未完成任何人工抽样确认")
    if intersection_p0:
        phase2_blockers.append("主席台 road/building P0 Geometry 歧义仍未解决")

    phase3_blockers = []
    if not layers["entrances"]:
        phase3_blockers.append("Formal Entrance 为 0，无法可靠选择建筑入口")
    if topology_p0:
        phase3_blockers.append(f"仍有 {topology_p0} 个 P0 topology gap endpoint")
    phase3_blockers.append("道路/校门通行属性和无障碍属性仍有 UNKNOWN")

    non_blocking = [
        f"{sum(item['properties'].get('height') is None for item in buildings)} 栋建筑高度保持 NULL，2.5D 使用安全 fallback",
        f"{naming['hiddenTotalLabels']} 个 generic/ambiguous/overlong 标签已隐藏但 Geometry 保留",
        "P1/P2 topology warnings 保留为后续现场核验工作集",
        "商业 POI 时效性尚未逐一现场复核",
    ]
    ready = not phase2_blockers
    core_building = topology["qualityMetrics"]["coreBuildingVerification"]
    core_poi = topology["qualityMetrics"]["corePoiVerification"]
    summary = {
        "manualReviewedCount": manual_reviewed,
        "fieldVerifiedCount": field_verified,
        "confirmedDormitories": len(dormitories),
        "pendingDormitories": naming["dormitoryCandidates"] - len(dormitories),
        "formalEntrances": len(layers["entrances"]),
        "gateVerification": {"reviewed": sum(_reviewed(item) for item in gates), "required": 2},
        "p0TopologyRemaining": topology_p0,
        "roadBuildingP0Remaining": intersection_p0,
        "phase2BlockerCount": len(phase2_blockers),
        "phase3BlockerCount": len(phase3_blockers),
        "phase2Ready": ready,
        "warningClassification": {
            "BLOCKS_PHASE_2": phase2_blockers,
            "BLOCKS_PHASE_3": phase3_blockers,
            "NON_BLOCKING": non_blocking,
        },
    }

    docs_dir = dataset_dir.parents[2] / "docs"
    readiness = f"""# Phase 2 Data Readiness

Generated by the Phase 1.7 GIS pipeline on {date.today().isoformat()}. A source-backed OSM/official name remains `SOURCE_VERIFIED`; only explicit user review or field evidence may promote it.

## Ready items

- {validation['valid']} normalized GIS objects pass Geometry, WGS84 range, stable-ID and campus-buffer validation.
- {sum(bool(_display(item)) for item in buildings)}/{len(buildings)} Buildings have a displayName; generic and ambiguous labels are suppressed.
- Building and POI semantics are separated, with {naming['linkedPois']} POIs linked to a Building.
- `officialName`, `displayName`, aliases, category and buildingId are available for future search implementation.

## Manual verification coverage

| Metric | Result |
|---|---:|
| MANUALLY_REVIEWED objects | {manual_reviewed} |
| FIELD_VERIFIED objects | {field_verified} |
| Core Buildings | {core_building['reviewed']}/{core_building['total']} |
| Core POIs | {core_poi['reviewed']}/{core_poi['total']} |
| Confirmed dormitories | {len(dormitories)}/{naming['dormitoryCandidates']} |
| Formal entrances | {len(layers['entrances'])} |
| Confirmed gates | {sum(_reviewed(item) for item in gates)}/2 |
| P0 topology endpoints remaining | {topology_p0} |
| Road/building P0 remaining | {intersection_p0} |

## Phase 2 blockers ({len(phase2_blockers)})

{chr(10).join(f'- {item}' for item in phase2_blockers) or '- None.'}

## Phase 3 blockers ({len(phase3_blockers)})

{chr(10).join(f'- {item}' for item in phase3_blockers) or '- None.'}

## Non-blocking limitations

{chr(10).join(f'- {item}' for item in non_blocking)}

## Decision

`PHASE_2_READY = {'YES' if ready else 'NO'}`

{'All Phase 2 data gates are satisfied.' if ready else ('No new user-confirmed campus facts were supplied in this review cycle. ' if not manual_reviewed and not field_verified else '') + 'The source-backed map remains usable for review, but PR #2 must stay Draft until the minimum manual checklist is completed.'}
"""
    (docs_dir / "PHASE_2_DATA_READINESS.md").write_text(readiness, encoding="utf-8")

    validation_path = docs_dir / "GIS_VALIDATION_REPORT.md"
    existing = validation_path.read_text(encoding="utf-8") if validation_path.is_file() else "# GIS Validation Report\n"
    marker = "## Phase 1.7 Validation v3"
    existing = existing.split(marker)[0].rstrip()
    phase17 = f"""

## Phase 1.7 Validation v3

- Valid objects: {validation['valid']}/{validation['total']}; errors: {validation['error']}; raw warnings: {validation['warning']}.
- MANUALLY_REVIEWED: {manual_reviewed}; FIELD_VERIFIED: {field_verified}.
- Confirmed dormitories: {len(dormitories)}/{naming['dormitoryCandidates']}; formal entrances: {len(layers['entrances'])}; confirmed gates: {sum(_reviewed(item) for item in gates)}/2.
- P0 topology endpoints unresolved: {topology_p0}; road/building P0 unresolved: {intersection_p0}.
- Warning impact: BLOCKS_PHASE_2 {len(phase2_blockers)} groups; BLOCKS_PHASE_3 {len(phase3_blockers)} groups; NON_BLOCKING {len(non_blocking)} groups.
- `PHASE_2_READY = {'YES' if ready else 'NO'}`. Details: `PHASE_2_DATA_READINESS.md`.
"""
    validation_path.write_text(existing + phase17, encoding="utf-8")
    return summary
